import "server-only";
import { getSupabaseAdminClient } from "@/lib/supabase/admin";
import { logError } from "@/lib/observability/logger";

/**
 * Records one affiliate-click event. Uses the service-role client
 * (`lib/supabase/admin.js`) because `affiliate_clicks` intentionally has
 * no INSERT policy for any session-based role — see migration §9's RLS
 * comment. Called from `app/go/[offerId]/route.js` only.
 *
 * Best-effort by design (§42): if this insert fails, the caller still
 * redirects the user — a lost analytics row must never block a purchase.
 * The one thing that must NOT be fabricated is the ClickID itself
 * (`click_uuid`), which is generated by the caller via
 * `crypto.randomUUID()` before this is called, not derived here.
 *
 * @param {object} params
 * @returns {Promise<{ ok: boolean, error?: string }>}
 */
export async function recordAffiliateClick({
  clickUuid,
  offerId,
  productId,
  storeId,
  userId,
  sessionId,
  isBot,
  userAgent,
  referrer,
  trackingParam,
  redirectStatus = "redirected",
  requestId,
}) {
  try {
    const supabase = getSupabaseAdminClient();
    const { error } = await supabase.from("affiliate_clicks").insert({
      click_uuid: clickUuid,
      offer_id: offerId,
      product_id: productId,
      store_id: storeId,
      user_id: userId || null,
      session_id: sessionId || null,
      is_bot: !!isBot,
      // Truncate defensively — this is a classification signal, not a
      // field that needs the full raw string preserved (§43 data
      // minimization).
      user_agent: userAgent ? userAgent.slice(0, 500) : null,
      referrer: referrer ? referrer.slice(0, 500) : null,
      tracking_param: trackingParam || null,
      redirect_status: redirectStatus,
      // PART 6 §47: the request correlation id, not any other tracing
      // data — `affiliate_clicks.metadata` already existed (Part 4) as a
      // general-purpose jsonb column, so this needs no schema change.
      metadata: requestId ? { requestId } : {},
    });
    if (error) {
      logError("recordAffiliateClick failed", { requestId, error: error.message });
      return { ok: false, error: error.message };
    }
    return { ok: true };
  } catch (err) {
    logError("recordAffiliateClick threw", { requestId, error: String(err) });
    return { ok: false, error: String(err) };
  }
}

/**
 * Records one product-view event. Same best-effort, non-blocking
 * contract as above — called from `app/api/track/view/route.js`, which
 * is itself fired with `keepalive` and never awaited by the page (§25).
 */
export async function recordProductViewEvent({ productId, userId, sessionId, isBot, referrer }) {
  try {
    const supabase = getSupabaseAdminClient();
    const { error } = await supabase.from("product_views").insert({
      product_id: productId,
      user_id: userId || null,
      session_id: sessionId || null,
      is_bot: !!isBot,
      referrer: referrer ? referrer.slice(0, 500) : null,
    });
    if (error) {
      console.error("recordProductViewEvent:", error.message);
      return { ok: false };
    }
    return { ok: true };
  } catch (err) {
    console.error("recordProductViewEvent threw:", err);
    return { ok: false };
  }
}
