/**
 * STANDALONE DEMO MOCK DATA
 * 
 * Provides complete in-memory mock data for the demo version of Affiliate Demo.
 * 100% independent of Supabase — no database needed!
 */

export const MOCK_DEPARTMENTS = [
  { slug: "men", name: "Men", kind: "department", sort_order: 1 },
  { slug: "women", name: "Women", kind: "department", sort_order: 2 },
  { slug: "kids", name: "Kids", kind: "department", sort_order: 3 },
];

export const MOCK_SUBCATEGORIES = [
  { slug: "t-shirts", name: "T-Shirts", kind: "subcategory", sort_order: 1 },
  { slug: "shirts", name: "Shirts", kind: "subcategory", sort_order: 2 },
  { slug: "jeans", name: "Jeans", kind: "subcategory", sort_order: 3 },
  { slug: "hoodies", name: "Hoodies", kind: "subcategory", sort_order: 4 },
  { slug: "jackets", name: "Jackets", kind: "subcategory", sort_order: 5 },
  { slug: "trousers", name: "Trousers", kind: "subcategory", sort_order: 6 },
  { slug: "dresses", name: "Dresses", kind: "subcategory", sort_order: 7 },
  { slug: "tops", name: "Tops", kind: "subcategory", sort_order: 8 },
];

export const MOCK_BRANDS = [
  { name: "Affiliate Demo Basics", slug: "cloxtro-basics" },
  { name: "Northline", slug: "northline" },
  { name: "Aster & Co", slug: "aster-co" },
  { name: "Fieldstone", slug: "fieldstone" },
  { name: "Marrow", slug: "marrow" },
  { name: "Lucid", slug: "lucid" },
  { name: "Kinfolk", slug: "kinfolk" },
  { name: "Aro Studio", slug: "aro-studio" },
];

export const MOCK_STORES = [
  { id: "store-1", name: "Amazon India", slug: "amazon", baseUrl: "https://amazon.in" },
  { id: "store-2", name: "Myntra", slug: "myntra", baseUrl: "https://myntra.com" },
  { id: "store-3", name: "Ajio Luxe", slug: "ajio", baseUrl: "https://ajio.com" },
  { id: "store-4", name: "Tata CLiQ", slug: "tatacliq", baseUrl: "https://tatacliq.com" },
  { id: "store-5", name: "Brand Direct", slug: "direct", baseUrl: "https://brand.test" },
];

export const MOCK_PRODUCTS = [
  {
    id: "p-0001",
    name: "Essential Heavyweight Crew Tee",
    slug: "essential-heavyweight-crew-tee",
    brand: "Affiliate Demo Basics",
    category: "men",
    subcategory: "t-shirts",
    description: "Premium 240 GSM combed organic cotton t-shirt with a structured drape and relaxed fit.",
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=1067&fit=crop&auto=format&q=80",
      "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&h=1067&fit=crop&auto=format&q=80",
    ],
    offerId: "off-0001",
    price: 499,
    originalPrice: 999,
    discountPercentage: 50,
    rating: 4.6,
    reviewCount: 248,
    colors: [
      { name: "Black", hex: "#1a1a1a" },
      { name: "Off-White", hex: "#f5f3ee" },
      { name: "Olive Green", hex: "#4b5320" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    material: "100% Organic Cotton",
    fit: "Relaxed",
    occasion: "Casual",
    tags: ["bestseller", "trending", "deal"],
    availability: "in_stock",
    store: "Amazon India",
    affiliateUrl: "https://amazon.in",
    badges: ["Bestseller", "50% OFF"],
    createdAt: "2026-01-15T08:00:00.000Z",
    updatedAt: "2026-03-01T10:00:00.000Z",
  },
  {
    id: "p-0002",
    name: "Relaxed Linen Blend Wrap Dress",
    slug: "relaxed-linen-blend-wrap-dress",
    brand: "Aster & Co",
    category: "women",
    subcategory: "dresses",
    description: "Breathable European flax linen-cotton wrap dress designed with an adjustable waist tie and midi length.",
    images: [
      "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&h=1067&fit=crop&auto=format&q=80",
      "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=800&h=1067&fit=crop&auto=format&q=80",
    ],
    offerId: "off-0002",
    price: 1899,
    originalPrice: 2999,
    discountPercentage: 37,
    rating: 4.8,
    reviewCount: 172,
    colors: [
      { name: "Sand", hex: "#c9b491" },
      { name: "Sage", hex: "#9baf9b" },
    ],
    sizes: ["XS", "S", "M", "L"],
    material: "Linen Blend",
    fit: "Relaxed",
    occasion: "Everyday",
    tags: ["trending", "new"],
    availability: "in_stock",
    store: "Myntra",
    affiliateUrl: "https://myntra.com",
    badges: ["Trending", "New"],
    createdAt: "2026-02-10T12:00:00.000Z",
    updatedAt: "2026-03-10T14:30:00.000Z",
  },
  {
    id: "p-0003",
    name: "Classic Oxford Button-Down Shirt",
    slug: "classic-oxford-button-down-shirt",
    brand: "Northline",
    category: "men",
    subcategory: "shirts",
    description: "Traditional pinpoint Oxford cloth button-down with genuine pearlized buttons and tailored collar roll.",
    images: [
      "https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800&h=1067&fit=crop&auto=format&q=80",
      "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&h=1067&fit=crop&auto=format&q=80",
    ],
    offerId: "off-0003",
    price: 899,
    originalPrice: 1599,
    discountPercentage: 44,
    rating: 4.5,
    reviewCount: 310,
    colors: [
      { name: "Sky Blue", hex: "#87ceeb" },
      { name: "White", hex: "#ffffff" },
      { name: "Navy", hex: "#000080" },
    ],
    sizes: ["38", "40", "42", "44"],
    material: "100% Cotton",
    fit: "Regular",
    occasion: "Formal",
    tags: ["bestseller", "deal"],
    availability: "in_stock",
    store: "Ajio Luxe",
    affiliateUrl: "https://ajio.com",
    badges: ["Bestseller"],
    createdAt: "2026-01-05T09:00:00.000Z",
    updatedAt: "2026-03-12T11:00:00.000Z",
  },
  {
    id: "p-0004",
    name: "Vintage Wash Straight Leg Denim",
    slug: "vintage-wash-straight-leg-denim",
    brand: "Northline",
    category: "men",
    subcategory: "jeans",
    description: "Rugged 13.5oz ring-spun denim with a vintage indigo tint and classic five-pocket construction.",
    images: [
      "https://images.unsplash.com/photo-1542060748-10c28b62716f?w=800&h=1067&fit=crop&auto=format&q=80",
      "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&h=1067&fit=crop&auto=format&q=80",
    ],
    offerId: "off-0004",
    price: 1299,
    originalPrice: 2499,
    discountPercentage: 48,
    rating: 4.3,
    reviewCount: 94,
    colors: [
      { name: "Vintage Blue", hex: "#3b5998" },
      { name: "Washed Black", hex: "#2b2b2b" },
    ],
    sizes: ["30", "32", "34", "36"],
    material: "Denim",
    fit: "Straight",
    occasion: "Casual",
    tags: ["trending", "deal"],
    availability: "in_stock",
    store: "Amazon India",
    affiliateUrl: "https://amazon.in",
    badges: ["Trending"],
    createdAt: "2026-01-20T10:00:00.000Z",
    updatedAt: "2026-03-05T15:00:00.000Z",
  },
  {
    id: "p-0005",
    name: "Cozy Fleece Pullover Hoodie (Kids)",
    slug: "cozy-fleece-pullover-hoodie-kids",
    brand: "Fieldstone",
    category: "kids",
    subcategory: "hoodies",
    description: "Brushed-back cotton-rich fleece pullover with double-layer hood and kangaroo pouch pocket.",
    images: [
      "https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?w=800&h=1067&fit=crop&auto=format&q=80",
    ],
    offerId: "off-0005",
    price: 599,
    originalPrice: 1199,
    discountPercentage: 50,
    rating: 4.7,
    reviewCount: 88,
    colors: [
      { name: "Heather Grey", hex: "#9e9e9e" },
      { name: "Navy", hex: "#1a237e" },
      { name: "Mustard", hex: "#e1ad01" },
    ],
    sizes: ["4-5Y", "6-7Y", "8-9Y", "10-11Y"],
    material: "Cotton Blend",
    fit: "Relaxed",
    occasion: "Casual",
    tags: ["new", "deal"],
    availability: "in_stock",
    store: "Tata CLiQ",
    affiliateUrl: "https://tatacliq.com",
    badges: ["50% OFF", "New"],
    createdAt: "2026-02-15T11:00:00.000Z",
    updatedAt: "2026-03-08T16:00:00.000Z",
  },
  {
    id: "p-0006",
    name: "Oversized Minimalist Bomber Jacket",
    slug: "oversized-minimalist-bomber-jacket",
    brand: "Marrow",
    category: "men",
    subcategory: "jackets",
    description: "Water-resistant matte nylon shell with lightweight thermal fill and chunky double-ended zipper.",
    images: [
      "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=800&h=1067&fit=crop&auto=format&q=80",
      "https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=800&h=1067&fit=crop&auto=format&q=80",
    ],
    offerId: "off-0006",
    price: 2499,
    originalPrice: 4999,
    discountPercentage: 50,
    rating: 4.9,
    reviewCount: 142,
    colors: [
      { name: "Olive Green", hex: "#404a37" },
      { name: "Onyx Black", hex: "#0f0f0f" },
    ],
    sizes: ["S", "M", "L", "XL"],
    material: "Nylon Shell",
    fit: "Oversized",
    occasion: "Streetwear",
    tags: ["trending", "deal"],
    availability: "in_stock",
    store: "Ajio Luxe",
    affiliateUrl: "https://ajio.com",
    badges: ["Trending", "Top Rated"],
    createdAt: "2026-01-18T14:00:00.000Z",
    updatedAt: "2026-03-14T09:00:00.000Z",
  },
  {
    id: "p-0007",
    name: "Tailored Pleated Trousers",
    slug: "tailored-pleated-trousers",
    brand: "Lucid",
    category: "men",
    subcategory: "trousers",
    description: "Single forward-pleat trousers with internal waistband curtain, slanted front pockets and blind hem.",
    images: [
      "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&h=1067&fit=crop&auto=format&q=80",
    ],
    offerId: "off-0007",
    price: 1499,
    originalPrice: 2199,
    discountPercentage: 32,
    rating: 4.4,
    reviewCount: 63,
    colors: [
      { name: "Charcoal Grey", hex: "#36454f" },
      { name: "Taupe Khaki", hex: "#b38b6d" },
    ],
    sizes: ["30", "32", "34", "36"],
    material: "Poly-Viscose Blend",
    fit: "Tailored",
    occasion: "Smart Casual",
    tags: ["new"],
    availability: "in_stock",
    store: "Myntra",
    affiliateUrl: "https://myntra.com",
    badges: ["New"],
    createdAt: "2026-02-01T12:00:00.000Z",
    updatedAt: "2026-03-02T13:00:00.000Z",
  },
  {
    id: "p-0008",
    name: "Ribbed Knit Sleeveless Top",
    slug: "ribbed-knit-sleeveless-top",
    brand: "Kinfolk",
    category: "women",
    subcategory: "tops",
    description: "Fine gauge modal-cotton ribbed sleeveless top with high crew neck and clean bind finish.",
    images: [
      "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&h=1067&fit=crop&auto=format&q=80",
    ],
    offerId: "off-0008",
    price: 399,
    originalPrice: 799,
    discountPercentage: 50,
    rating: 4.6,
    reviewCount: 119,
    colors: [
      { name: "Cream", hex: "#fffdd0" },
      { name: "Espresso", hex: "#362b28" },
    ],
    sizes: ["XS", "S", "M", "L"],
    material: "Modal Cotton",
    fit: "Slim",
    occasion: "Casual",
    tags: ["bestseller", "deal"],
    availability: "in_stock",
    store: "Amazon India",
    affiliateUrl: "https://amazon.in",
    badges: ["Under ₹499", "Bestseller"],
    createdAt: "2026-01-25T16:00:00.000Z",
    updatedAt: "2026-03-11T17:00:00.000Z",
  },
  {
    id: "p-0009",
    name: "Floral Tiered Midi Sundress",
    slug: "floral-tiered-midi-sundress",
    brand: "Aster & Co",
    category: "women",
    subcategory: "dresses",
    description: "Flowing lightweight chiffon sundress featuring subtle hand-painted botanical prints and ruffle hem.",
    images: [
      "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=800&h=1067&fit=crop&auto=format&q=80",
    ],
    offerId: "off-0009",
    price: 1599,
    originalPrice: 2899,
    discountPercentage: 45,
    rating: 4.7,
    reviewCount: 84,
    colors: [
      { name: "Blush Pink", hex: "#ffd1dc" },
      { name: "Cornflower Blue", hex: "#6495ed" },
    ],
    sizes: ["S", "M", "L"],
    material: "Chiffon",
    fit: "Regular",
    occasion: "Everyday",
    tags: ["trending"],
    availability: "in_stock",
    store: "Myntra",
    affiliateUrl: "https://myntra.com",
    badges: ["Trending"],
    createdAt: "2026-02-12T10:00:00.000Z",
    updatedAt: "2026-03-09T18:00:00.000Z",
  },
  {
    id: "p-0010",
    name: "Heavyweight Boxy Graphic Tee",
    slug: "heavyweight-boxy-graphic-tee",
    brand: "Aro Studio",
    category: "men",
    subcategory: "t-shirts",
    description: "260 GSM drop-shoulder streetwear tee with high-density architectural typography print on chest.",
    images: [
      "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&h=1067&fit=crop&auto=format&q=80",
    ],
    offerId: "off-0010",
    price: 699,
    originalPrice: 1299,
    discountPercentage: 46,
    rating: 4.8,
    reviewCount: 198,
    colors: [
      { name: "Washed Vintage Grey", hex: "#5a5a5a" },
      { name: "Jet Black", hex: "#111111" },
    ],
    sizes: ["S", "M", "L", "XL"],
    material: "100% Combed Cotton",
    fit: "Oversized",
    occasion: "Streetwear",
    tags: ["trending", "new"],
    availability: "in_stock",
    store: "Ajio Luxe",
    affiliateUrl: "https://ajio.com",
    badges: ["Trending", "New"],
    createdAt: "2026-02-20T08:00:00.000Z",
    updatedAt: "2026-03-15T12:00:00.000Z",
  },
  {
    id: "p-0011",
    name: "Active Cotton Jogger Pants (Kids)",
    slug: "active-cotton-jogger-pants-kids",
    brand: "Fieldstone",
    category: "kids",
    subcategory: "trousers",
    description: "Reinforced knee joggers made from durable stretch French terry with elastic drawstring waist.",
    images: [
      "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=800&h=1067&fit=crop&auto=format&q=80",
    ],
    offerId: "off-0011",
    price: 449,
    originalPrice: 899,
    discountPercentage: 50,
    rating: 4.4,
    reviewCount: 76,
    colors: [
      { name: "Navy", hex: "#191970" },
      { name: "Melange Grey", hex: "#808080" },
    ],
    sizes: ["4-5Y", "6-7Y", "8-9Y"],
    material: "Cotton Stretch",
    fit: "Regular",
    occasion: "Casual",
    tags: ["bestseller", "deal"],
    availability: "in_stock",
    store: "Tata CLiQ",
    affiliateUrl: "https://tatacliq.com",
    badges: ["Under ₹499", "Bestseller"],
    createdAt: "2026-01-28T09:00:00.000Z",
    updatedAt: "2026-03-04T10:00:00.000Z",
  },
  {
    id: "p-0012",
    name: "Trucker Denim Jacket Sherpa Collar",
    slug: "trucker-denim-jacket-sherpa-collar",
    brand: "Northline",
    category: "men",
    subcategory: "jackets",
    description: "Iconic trucker silhouette in stonewash blue with warm faux-shearling lining on collar and body.",
    images: [
      "https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=800&h=1067&fit=crop&auto=format&q=80",
    ],
    offerId: "off-0012",
    price: 2199,
    originalPrice: 3999,
    discountPercentage: 45,
    rating: 4.7,
    reviewCount: 154,
    colors: [
      { name: "Stonewash Blue", hex: "#4682b4" },
    ],
    sizes: ["M", "L", "XL"],
    material: "Denim & Sherpa",
    fit: "Regular",
    occasion: "Casual",
    tags: ["trending"],
    availability: "in_stock",
    store: "Amazon India",
    affiliateUrl: "https://amazon.in",
    badges: ["Trending"],
    createdAt: "2026-01-10T11:00:00.000Z",
    updatedAt: "2026-03-01T15:00:00.000Z",
  },
];
